apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
  labels:
    app: bloggingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloggingapp
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
        - name: bloggingapp
          image: akshay196/fullstack-webapp:v1 # Make sure the private image exists
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:                  # Added readiness probe to ensure app is ready before routing traffic
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:                   # Added liveness probe for periodic health checks
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      imagePullSecrets:
        - name: regcred # Ensure this secret is created for private DockerHub image access

---
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc
spec:
  selector:
    app: bloggingapp
  ports:
    - protocol: "TCP"
      port: 80              # Public port exposed by the load balancer
      targetPort: 8080       # Port inside the container
  type: LoadBalancer         # Ensures a public IP is provisioned for the service
